### ISSUE TITLE
Fetching endpoint returns old data

### ISSUE THREAD

**Issue by shintaii** [woocommerce/wc-api-python#51] opened 2020-05-16 15:03 UTC
When doing a get request on, for example 'wc/v3/products/3895/variations/3899'

It returns old data. When doing the same request using, for example, postman, i get the newest version/

Postman result:
`
    "id": 3899,
    "date_created": "2020-05-16T12:21:21",
    "date_created_gmt": "2020-05-16T12:21:21",
    "date_modified": "2020-05-16T13:51:46",
    "date_modified_gmt": "2020-05-16T13:51:46",
    "description": "",
`

Python result:
`
    'id': 3899, 
    'date_created': '2020-05-16T12:21:21', 
    'date_created_gmt': '2020-05-16T12:21:21', 
    'date_modified': '2020-05-16T12:32:35', 
    'date_modified_gmt': '2020-05-16T12:32:35', 
    'description': ''
`

**Comment by claudiosanches** [comment] 2021-03-13 19:29
Hello, I can't reproduce it testing with latest version of this library, you could try change user agent in case there's some cache.
Closing since I can't reproduce and sounds like an issue related to cache in the server your are requesting, since there's no means to request older data by default.

**Closed by claudiosanches** 2021-03-13 19:29 UTC
